<?php
/**
 * @see Valibus_Landing_Block_Popin
 * @var $this Valibus_Landing_Block_Popin
 */
?>

<?php //if ($this->canShow()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var messagePopupClosed = false;
        function openMessagePopup() {
            //var height = $('html-body').getHeight();

            var height = $$('body').first().getHeight();

            $('message-popup-window-mask').setStyle({'height':height + 'px'});
            toggleSelectsUnderBlock($('message-popup-window-mask'), false);
            Element.show('message-popup-window-mask');
            $('message-popup-window').addClassName('show');
        }

        function closeMessagePopup() {
            toggleSelectsUnderBlock($('message-popup-window-mask'), true);
            Element.hide('message-popup-window-mask');
            $('message-popup-window').removeClassName('show');
            messagePopupClosed = true;
        }

        Event.observe(window, 'load', openMessagePopup);
        Event.observe(window, 'keyup', function (evt) {
            if (messagePopupClosed) return;
            var code;
            if (evt.keyCode) code = evt.keyCode;
            else if (evt.which) code = evt.which;
            if (code == Event.KEY_ESC) {
                closeMessagePopup();
            }
        });
        function toggleSelectsUnderBlock(block, flag) {
            if (Prototype.Browser.IE) {
                var selects = document.getElementsByTagName("select");
                for (var i = 0; i < selects.length; i++) {
                    /**
                     * @todo: need check intersection
                     */
                    if (flag) {
                        if (selects[i].needShowOnSuccess) {
                            selects[i].needShowOnSuccess = false;
                            // Element.show(selects[i])
                            selects[i].style.visibility = '';
                        }
                    }
                    else {
                        if (Element.visible(selects[i])) {
                            // Element.hide(selects[i]);
                            selects[i].style.visibility = 'hidden';
                            selects[i].needShowOnSuccess = true;
                        }
                    }
                }
            }
        }
        //]]>
    </script>
    <!-- Zone de filigrane transparent de la popin -->
    <div id="message-popup-window-mask" style="display:none;"></div>
    <!-- Contenu de la popin -->
    <div id="message-popup-window" class="message-popup">
        <!-- ligne d'en tete, titre + bouton fermeture -->
        <div class="message-popup-head">
            <a href="#" onclick="closeMessagePopup(); return false;"
               title="<?php echo $this->__('Close the social ask.'); ?>"><span>X</span></a>

            <h2><?php echo $this->__('Stay tunned : Get social connected !'); ?></h2>
        </div>
        <!-- Contenu popin -->
        <div class="message-popup-content">
            <?php
            $linesToDisplay=$this->getContent();
            foreach($linesToDisplay as $key => $line){
                if ($key=="error"){
                    die ("error".$line);
                }elseif($key=="static"){
                    echo $line;
                }else{
                    echo '<div class="social-plugin">'.$line.'</div>';
                }
            }
            ?>
        </div>
        <!-- Fin de la zone -->
    </div>

    <!--FIN ZONE POPIN -->
<?php //endif; ?>