<?php
/**
 * @see Valibus_Landing_Block_Popin
 */
?>
<?php if ($this->canShow()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var messagePopupClosed = false;
        function openMessagePopup() {
            //var height = $('html-body').getHeight();

            var height = $$('body').first().getHeight();

            $('message-popup-window-mask').setStyle({'height':height + 'px'});
            toggleSelectsUnderBlock($('message-popup-window-mask'), false);
            Element.show('message-popup-window-mask');
            $('message-popup-window').addClassName('show');
        }

        function closeMessagePopup() {
            toggleSelectsUnderBlock($('message-popup-window-mask'), true);
            Element.hide('message-popup-window-mask');
            $('message-popup-window').removeClassName('show');
            messagePopupClosed = true;
        }

        Event.observe(window, 'load', openMessagePopup);
        Event.observe(window, 'keyup', function (evt) {
            if (messagePopupClosed) return;
            var code;
            if (evt.keyCode) code = evt.keyCode;
            else if (evt.which) code = evt.which;
            if (code == Event.KEY_ESC) {
                closeMessagePopup();
            }
        });
        function toggleSelectsUnderBlock(block, flag) {
            if (Prototype.Browser.IE) {
                var selects = document.getElementsByTagName("select");
                for (var i = 0; i < selects.length; i++) {
                    /**
                     * @todo: need check intersection
                     */
                    if (flag) {
                        if (selects[i].needShowOnSuccess) {
                            selects[i].needShowOnSuccess = false;
                            // Element.show(selects[i])
                            selects[i].style.visibility = '';
                        }
                    }
                    else {
                        if (Element.visible(selects[i])) {
                            // Element.hide(selects[i]);
                            selects[i].style.visibility = 'hidden';
                            selects[i].needShowOnSuccess = true;
                        }
                    }
                }
            }
        }
        //]]>
    </script>
    <!-- Zone de filigrane transparent de la popin -->
    <div id="message-popup-window-mask" style="display:none;"></div>
    <!-- Contenu de la popin -->
    <div id="message-popup-window" class="message-popup">
        <!-- ligne d'en tete, titre + bouton fermeture -->
        <div class="message-popup-head">
            <a href="#" onclick="closeMessagePopup(); return false;"
               title="<?php echo $this->getPopinCloseText(); ?>"><span>X</span></a>

            <h2><?php echo $this->getPopinTitle(); ?></h2>
        </div>
        <!-- Contenu popin -->
        <div class="message-popup-content">
            <div class="social-plugin">
                <div id="fb-root"></div>
                <script>(function(d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1";
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                <div class="fb-follow" data-href="https://www.facebook.com/valibusseo" data-show-faces="true" data-width="350"></div>
                <br />
            </div>
            <div class="message social-plugin">
                <!-- Contenu de la zone -->
                <a href="https://twitter.com/PatrickValibus" class="twitter-follow-button" data-show-count="true"
                   data-lang="fr" data-size="large">Follow @Patrickvalibus</a>
                <script>!function (d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (!d.getElementById(id)) {
                            js = d.createElement(s);
                            js.id = id;
                            js.src = "//platform.twitter.com/widgets.js";
                            fjs.parentNode.insertBefore(js, fjs);
                        }
                    }(document, "script", "twitter-wjs");</script>
            </div>

            <div class="social-plugin"><!-- Placez cette balise où vous souhaitez faire apparaître le gadget badge. -->
                <div class="g-plus" data-height="69" data-href="//plus.google.com/114790663510802931185"
                     data-rel="author"></div>

                <!-- Placez cette ballise après la dernière balise badge. -->
                <script type="text/javascript">
                    window.___gcfg = {lang:'fr'};

                    (function () {
                        var po = document.createElement('script');
                        po.type = 'text/javascript';
                        po.async = true;
                        po.src = 'https://apis.google.com/js/plusone.js';
                        var s = document.getElementsByTagName('script')[0];
                        s.parentNode.insertBefore(po, s);
                    })();
                </script>
            </div>
        </div>
        <!-- Fin de la zone -->
    </div>

    <!--FIN ZONE POPIN -->
<?php endif; ?>